#!/usr/bin/env bash

dir='/tmp/rund'

fatal(){
    echo "ERROR: $1" >&2
    exit 1
}

status() {
  echo 'status' > "$dir/command"

  sleep 1

  cat "$dir/status"
}

run() {
  echo "$(pwd)/$1"
  echo 'run' >"$dir/command"
  sleep 0
  echo -n "$(pwd)/$1" >"$dir/command"
  sleep 0
}

exit_fn() {
  echo 'exit' >"$dir/command"
}

main(){
    if [[ -d $dir ]]; then 
        case "$1" in
        '')
          echo 'Please specify a command'
          exit 1
          ;;
        'exit')
          exit_fn
          ;;
        'status')
          status
          ;;
        'run')
          run "$2"
          ;;
        *)
          echo 'Invalid Command!'
          exit 1
          ;;
        esac
    else
        echo "Error: Can not connect to server."
        return 1
    fi
}

main "$@"
