#!/usr/bin/env bash

fd='/tmp/rund/command'

fatal(){
    echo "ERROR: $1" >&2
    exit 1
}

status() {
  echo 'status' > "$fd"

  sleep 1

  cat "${fd%/*}/status"
}

run() {
  echo "$(pwd)/$1"
  echo 'run' >"$fd"
  sleep 0
  echo -n "$(pwd)/$1" >"$fd"
  sleep 0
}

exit_fn() {
  echo 'exit' >"$fd"
}

main(){
	case "$1" in
	'')
	  echo 'Please specify a command'
	  exit 1
	  ;;
	'exit')
	  exit_fn
	  ;;
	'status')
	  status
	  ;;
	'run')
	  run "$2"
	  ;;
	*)
	  echo 'Invalid Command!'
	  exit 1
	  ;;
	esac
}

main "$@"
